# Generated by Django 3.2.15 on 2022-09-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/%Y/%m/%d/'),
        ),
    ]
